ejemplo1:
	rustc -A warnings input1.rs -o input1 && ./input1 && rm input1

ejemplo2:
	rustc -A warnings input2.rs -o input2 && ./input2 && rm input2

ejemplo3:
	rustc -A warnings input3.rs -o input3 && ./input3 && rm input3

ejemplo4:
	rustc -A warnings input4.rs -o input4 && ./input4 && rm input4