ejemplo1:
	fpc input1.pas && ./input1 && rm input1 && rm input1.o

ejemplo2:
	fpc input2.pas && ./input2 && rm input2 && rm input2.o

ejemplo3:
	fpc input3.pas && ./input3 && rm input3 && rm input3.o

ejemplo4:
	fpc input4.pas && ./input4 && rm input4 && rm input4.o