ejemplo1:
	gcc input1.c -o input1 && ./input1 && rm input1

ejemplo2:
	gcc input2.c -o input2 && ./input2 && rm input2

ejemplo3:
	gcc input3.c -o input3 && ./input3 && rm input3

ejemplo4:
	gcc input4.c -o input4 && ./input4 && rm input4